# Postgresql #
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/banking}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA #
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate.format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.jdbc.time_zone: ${JPA_TIMEZONE}
    properties:
      hibernate.default_schema: ${DB_NAME}

  # FLYWAY #
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/
    schemas: ${DB_NAME}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/banking}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

# Server #
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH}
